#!/usr/bin/env python3
# OFFLINE build tool (dev-only) — converts the client's "City wise Location
# template" workbook into social_store_templates.yaml, the store-address reply
# templates the social store flow sends. Run when the client updates the sheet.
#
#   python -m pip install openpyxl
#   python build_social_store_templates.py "City wise Location template - Checked.xlsx"
#
# Output shape (normalised keys — lowercased city/location):
#   verticals:
#     furniture:
#       cities:
#         bhubaneswar:
#           template: "<city-wide reply listing every store in the city>"
#           locations:
#             samantarapur: "<single-store reply>"
#             patia: "<single-store reply>"
#
# City-wise = the reply for "any store in <city>?" (lists all stores there).
# Location-wise = the reply for a specific locality / a pincode-resolved store.

import sys
from pathlib import Path

import openpyxl
import yaml

_OUT = Path(__file__).parent / "social_store_templates.yaml"
_VERT = {"furniture": "furniture", "full home customisation": "fhc", "doors": "doors"}


def _norm(s) -> str:
    return " ".join(str(s or "").strip().lower().split())


def _clean_template(t) -> str:
    # Sheet cells sometimes wrap the whole body in literal double-quotes.
    t = str(t or "").strip()
    if len(t) >= 2 and t[0] == '"' and t[-1] == '"':
        t = t[1:-1].strip()
    return t


def _col(ws, name):
    hdr = [str(ws.cell(1, c).value or "").strip().lower() for c in range(1, ws.max_column + 1)]
    for i, h in enumerate(hdr, 1):
        if h == name.lower():
            return i
    return None


def build(xlsx: str) -> None:
    wb = openpyxl.load_workbook(xlsx, data_only=True)
    data: dict = {}

    def vert_bucket(v):
        vk = _VERT.get(_norm(v))
        if not vk:
            return None
        return data.setdefault(vk, {}).setdefault("cities", {})

    # City-wise → cities[city].template
    ws = wb["City wise Location"]
    cV, cC, cT = _col(ws, "vertical"), _col(ws, "city"), _col(ws, "template")
    n_city = 0
    for r in range(2, ws.max_row + 1):
        cities = vert_bucket(ws.cell(r, cV).value)
        city, tpl = _norm(ws.cell(r, cC).value), _clean_template(ws.cell(r, cT).value)
        if cities is None or not city or not tpl:
            continue
        cities.setdefault(city, {})["template"] = tpl
        n_city += 1

    # Location-wise → cities[city].locations[location]
    ws = wb["Location wise"]
    cV, cC, cL, cT = (_col(ws, "vertical"), _col(ws, "city"),
                      _col(ws, "location"), _col(ws, "template"))
    n_loc = 0
    for r in range(2, ws.max_row + 1):
        cities = vert_bucket(ws.cell(r, cV).value)
        city, loc = _norm(ws.cell(r, cC).value), _norm(ws.cell(r, cL).value)
        tpl = _clean_template(ws.cell(r, cT).value)
        if cities is None or not city or not loc or not tpl:
            continue
        cities.setdefault(city, {}).setdefault("locations", {})[loc] = tpl
        n_loc += 1

    _OUT.write_text(
        "# Store-address reply templates for the social store flow. GENERATED by\n"
        "# build_social_store_templates.py from the client's 'City wise Location\n"
        "# template' sheet — do not hand-edit; regenerate.\n"
        + yaml.safe_dump({"verticals": data}, allow_unicode=True, sort_keys=True, width=10000))
    verts = {k: (len(v.get("cities", {})),
                 sum(len(c.get("locations", {})) for c in v.get("cities", {}).values()))
             for k, v in data.items()}
    print(f"wrote {_OUT.name}: {n_city} city + {n_loc} location templates")
    for k, (nc, nl) in verts.items():
        print(f"  {k}: {nc} cities, {nl} locations")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    build(sys.argv[1])
